/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author astru
 */
public class PublicSuperAtacados extends javax.swing.JFrame {

    /**
     * Creates new form PublicSuperAtacados
     */
    public int parar =0;
    public int ult=0;
    public PublicSuperAtacados() {
        initComponents();
        //dados cliente
        String nomecliente = JOptionPane.showInputDialog(null,"Digite seu nome: ");
        String contato = JOptionPane.showInputDialog(null,"Digite seu número de telefone ou e-mail: ");
        String cpf = JOptionPane.showInputDialog(null,"Digite seu CPF: ");
        
        JOptionPane.showMessageDialog(null,"Nome: "+nomecliente+"\n"+"Contato: "+contato+"\n"+"CPF: "+cpf);
        
    
}
    
  
public void somarValores() {
    try {
        double somaTotal = 0;
        for (int i = 1; i <= tabela.getRowCount(); i++) {

            somaTotal += Double.parseDouble(tabela.getValueAt(i, 4).toString());
            //AQUI VC JOGA PRO JTEXTFIELD
            max.setText("Subtotal: " + somaTotal);
        }
    } catch (NumberFormatException e) {
        System.out.println("Erro ao somar: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        max = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        precos = new javax.swing.JTextField();
        quants = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(66, 0, 204));
        jPanel1.setLayout(null);

        add.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        add.setText("Adicionar produto");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(20, 450, 270, 40);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Adicionar forma de pagamento");
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 400, 260, 30);

        max.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        max.setText("Subtotal: ");
        jPanel1.add(max);
        max.setBounds(340, 440, 160, 80);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Troco:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(640, 450, 150, 70);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("Cancelar compra");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(760, 520, 230, 39);
        jPanel1.add(precos);
        precos.setBounds(100, 280, 230, 30);
        jPanel1.add(quants);
        quants.setBounds(100, 340, 230, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Nome");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 220, 80, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Preço");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 270, 90, 48);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Quant.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 340, 100, 32);
        jPanel1.add(nomes);
        nomes.setBounds(100, 220, 230, 30);

        tabela.setAutoCreateRowSorter(true);
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço", "Quantidade", "Valor Indiv."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(340, 40, 440, 430);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setText("Deletar produto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 510, 270, 39);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 600);
        jPanel1.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(1016, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
            
        
            String nome=nomes.getText().trim();
            String precoshow=precos.getText();
            String quantshow=quants.getText();
            double preco=Double.parseDouble(precos.getText());
            int quant = Integer.parseInt(quants.getText());
            double conta1 = preco * quant;
            String res = ""+conta1;
            
            
            DefaultTableModel val = (DefaultTableModel) tabela.getModel();
            
            val.addRow(new String[]{nome,"R$"+precoshow,"x"+quantshow,"R$"+res});
            
            nomes.setText("");
            precos.setText("");
            quants.setText("");
            
            nomes.requestFocus();
            ult = (int) (ult +  conta1);
            
            somarValores();
        
    }//GEN-LAST:event_addActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked

    }//GEN-LAST:event_addMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        parar++;
        ult=0;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int posicao = tabela.getSelectedRow();
        tabela.remove(posicao);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PublicSuperAtacados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PublicSuperAtacados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PublicSuperAtacados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PublicSuperAtacados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PublicSuperAtacados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel max;
    private javax.swing.JTextField nomes;
    private javax.swing.JTextField precos;
    private javax.swing.JTextField quants;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
