/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import static java.lang.System.exit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author astru
 */
public final class PublicSuperAtacados extends javax.swing.JFrame {

    /**
     * Creates new form PublicSuperAtacados
     */
    public int parar =0;
    public int confir = 0;
    public double ult=0;
    public double dinheiro =0;
    public PublicSuperAtacados() {
        initComponents();
        //dados cliente
        String nomecliente = JOptionPane.showInputDialog(null,"Digite seu nome: ");
        String contato = JOptionPane.showInputDialog(null,"Digite seu número de telefone ou e-mail: ");
        String cpf = JOptionPane.showInputDialog(null,"Digite seu CPF: ");
        
        JOptionPane.showMessageDialog(null,"Nome: "+nomecliente+"\n"+"Contato: "+contato+"\n"+"CPF: "+cpf);
        
    
}
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        max = new javax.swing.JLabel();
        troco = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        precos = new javax.swing.JTextField();
        quants = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        op = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(66, 0, 204));
        jPanel1.setLayout(null);

        add.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        add.setText("Adicionar produto");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(20, 450, 270, 40);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Adicionar forma de pagamento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 400, 260, 30);

        max.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        max.setText("Subtotal: ");
        jPanel1.add(max);
        max.setBounds(340, 440, 160, 80);

        troco.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        troco.setText("Troco:");
        jPanel1.add(troco);
        troco.setBounds(640, 450, 150, 70);

        confirmar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        jPanel1.add(confirmar);
        confirmar.setBounds(340, 520, 230, 39);
        jPanel1.add(precos);
        precos.setBounds(100, 280, 230, 30);
        jPanel1.add(quants);
        quants.setBounds(100, 340, 230, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Nome");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 220, 80, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Preço");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 270, 90, 48);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Quant.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 340, 100, 32);
        jPanel1.add(nomes);
        nomes.setBounds(100, 220, 230, 30);

        tabela.setAutoCreateRowSorter(true);
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço", "Quantidade", "Valor Indiv."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(340, 40, 440, 430);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setText("Deletar produto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 520, 270, 39);
        jPanel1.add(op);
        op.setBounds(100, 190, 230, 16);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton5.setText("Cancelar compra");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(760, 520, 230, 39);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 600);
        jPanel1.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(1016, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
            
        
            String nome=nomes.getText().trim();
            double preco=Double.parseDouble(precos.getText());
            int quant = Integer.parseInt(quants.getText());
            double conta1 = preco * quant;
            String res = ""+conta1;
            
            
            DefaultTableModel val = (DefaultTableModel) tabela.getModel();
            
            val.addRow(new String[]{nome,"R$"+preco,"x"+quant,res});
            
            nomes.setText("");
            precos.setText("");
            quants.setText("");
            
            nomes.requestFocus();
            ult = ult +  conta1;
            max.setText("Subtotal: "+ult);
            
        
    }//GEN-LAST:event_addActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked

    }//GEN-LAST:event_addMouseClicked

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        if(confir != 1){
        JOptionPane.showMessageDialog(null, "Por favor, degite uma forma de pagamento");
        }else{
        JOptionPane.showMessageDialog(null,"Pagamento Concluido");
        exit(0);
        }
        
    }//GEN-LAST:event_confirmarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        if(tabela.getSelectedRow() != -1){
        String codigo = (String) tabela.getValueAt(tabela.getSelectedRow(), 3);
        double codigos=Double.parseDouble(codigo);
        ult = ult - codigos;
        max.setText("Subtotal: "+ult);
        DefaultTableModel val = (DefaultTableModel) tabela.getModel();
        val.removeRow(tabela.getSelectedRow());
        
        }else{
        JOptionPane.showMessageDialog(null, "Selecione um produto para excluir");
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String escolha = JOptionPane.showInputDialog(null,"Digite qual sua forma de pagamento: \n1 - Crédito \n2 - Débito \n3 - PIX \n 4 - Dinheiro");
        int x = Integer.parseInt(escolha);
        if(x ==1){
        op.setText("Opção Selecionada: Crédito");
        troco.setText("Troco: 0.0");
        confir = 1;
        }else if(x ==2){
            op.setText("Opção Selecionada: Dédito");
            troco.setText("Troco: 0.0");
            confir = 1;
        }else if(x==3){
        op.setText("Opção Selecionada: PIX");
        troco.setText("Troco: 0.0");
        confir = 1;
        }else if(x==4){
        op.setText("Opção Selecionada: Dinheiro");
        String digitar = JOptionPane.showInputDialog(null,"Digite o valor do pagamento: ");
        double y = Double.parseDouble(digitar);
        dinheiro = y - ult;
        if(y < ult){
        JOptionPane.showMessageDialog(null,"Dinheiro insuficiente");
        }else{
        troco.setText(""+dinheiro);
        confir = 1;
        }
        }else{
        JOptionPane.showMessageDialog(null,"Opção inválida");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PublicSuperAtacados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PublicSuperAtacados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PublicSuperAtacados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PublicSuperAtacados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PublicSuperAtacados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton confirmar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel max;
    private javax.swing.JTextField nomes;
    private javax.swing.JLabel op;
    private javax.swing.JTextField precos;
    private javax.swing.JTextField quants;
    private javax.swing.JTable tabela;
    private javax.swing.JLabel troco;
    // End of variables declaration//GEN-END:variables
}
